Try/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/

    url(r'^$', views.user_login, name='login'),

    url(r'^index$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    #  /music/712/
    # /music/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view() , name='album-delete'),

]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    #album_logo = models.CharField(max_length=1000)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + '-' + self.artist

class song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        login_fields = ['username','password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .models import Album
from .forms import UserForm, UserLoginForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


def user_login(request):
    user = False
    if request.method == 'POST':
        login_form = UserLoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request,user)
                request.session['username'] = username
                return redirect('music:index')
            else:
                return redirect('music:login')

    else:
        login_form = UserLoginForm()
    return render(request, 'music/login.html', {'login_form':login_form, 'user':user})


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #display blank form
    def get(self,request):
        form = self.form_class(None)
        user = False
        return render(request, self.template_name,{'form': form, 'user':user})

    #process form data
    def post(self,request):
        form = self.form_class(request.POST)
        user = form.save(commit=False)
        if form.is_valid():
            user = form.save(commit=False)

            #remove unwanted data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns user object if username and password are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form, 'user': user})


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
            <div class="panel-body">

                <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>


             </div>
         </div>
     </div>

    </div>
</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Album details {% endblock %}</title>
    {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">I-Music</a>
        </div>

        <!-- Items -->
    <div class ="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">

            {% if user.is_authenticated %}

            <li class="active">
                <a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                </a>
            </li>
            <li class="">
                <a href="#">
                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                </a>
            </li>
        </ul>

        <form class="navbar-form navbar-left" role="Search" method="get" action="#">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="">
            </div>
            <button type="submit" class="btn btn-default" >Search</button>
        </form>

        {% endif %}

        <ul class="nav navbar-nav navbar-right">

            {% if user.is_authenticated %}

             <li class="">
                <a href="{% url 'music:album-add' %}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
                </a>
            </li>

             <li class="">
                <a href="{% url 'music:login' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                </a>
            </li>

            {% else %}

            <li class="">
                <a href="{% url 'music:register' %}">
                    <span class="" aria-hidden="true"></span>&nbsp;Register
                </a>
            </li>

            <li class="">
                <a href="{% url 'music:login' %}">
                    <span class="" aria-hidden="true"></span>&nbsp;Login
                </a>
            </li>
        {% endif %}

        </ul>

        </div>

    </div>

</nav>
{% block body %}

{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
{#                <li role="presentation"><a href="{ % url 'music:create_song' album.id %}">Add New Song</a></li>#}
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'music:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group" xmlns="http://www.w3.org/1999/html">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
 </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body%}

	<div class="albums-container container-fluid">

	{% if all_albums %}
		<div id="products" class="row list-group">
			{% for album in all_albums %}

				<div class="col-sm-4 col-lg-2">
					<div class="thumbnail">
						<a href="{% url 'music:detail' album.id %}">
							<img src="{{ album.album_logo.url }}" class="img-responsive">
						</a>
						<div class="caption">
							<h2>{{ album.album_title }}</h2>
							<h4>{{ album.artist }}</h4>

							<!-- View Details -->
							<a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

							<!-- Delete Album -->
							<form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
								{% csrf_token %}
								<input type="hidden" name="album_id" value="{{ album.id }}" />
								<button type="submit" class="btn btn-default btn-sm">
									<span class="glyphicon glyphicon-trash"></span>
								</button>

							</form>

							<!-- Favourite Album -->
							<a href="#" class="btn btn-default btn-sm btn-favourite" role="button">
								<span class="glyphicon glyphicon-star"></span>
							</a>
						</div>
					</div>
				</div>

			{% endfor %}
		</div>


	{% else %}

	{% endif %}



	</div>



{% endblock%}

music/templates/music/login.html
{% extends 'music/base.html' %}
{% block title %}Login{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
            <div class="panel-body">
                <h3>Login</h3>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in login_form %}
                    <div class="form-group" xmlns="http://www.w3.org/1999/html">
                        <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{ field.errors }}</span>
                        </div>
                        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
                        <div class="col-sm-10">{{ field }}</div>
                     </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>


             </div>
         </div>
     </div>

    </div>
</div>

{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
            <div class="panel-body">
                <h3>Create a NEW Account</h3>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>


             </div>
         </div>
     </div>

    </div>
</div>

{% endblock %}